name: flexibase-db-stack
version: '3.8'
services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - ${FLEXIBASE_DB_EXPOSE_PORT}:${FLEXIBASE_DB_EXPOSE_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${FLEXIBASE_ADMIN_PASSWORD}
      - MYSQL_DATABASE=${FLEXIBASE_DB_NAME}
      - MYSQL_USER=${FLEXIBASE_ADMIN_USER}
      - MYSQL_PASSWORD=${FLEXIBASE_ADMIN_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  flexibase-db:
    build: .
    container_name: flexibase-db
    ports:
      - ${FLEXIBASE_DB_EXPOSE_PORT}:5000
    environment:
      - FLEXIBASE_DB_EXPOSE_PORT=${FLEXIBASE_DB_EXPOSE_PORT}
      - FLEXIBASE_ADMIN_USER=${FLEXIBASE_ADMIN_USER}
      - FLEXIBASE_ADMIN_PASSWORD=${FLEXIBASE_ADMIN_PASSWORD}
      - FLEXIBASE_DB_HOST="mysql"
    depends_on:
      - mysql
    restart: unless-stopped
      
volumes:
  mysql-data:

networks:
  default:
    name: flexibase-auth-network
